# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod
mod_id=modularrouters
archive_base_name=modular-routers
mod_version=26.2.0.1
mod_name="Modular Routers"
mod_group_id=me.desht.modularrouters
mod_license=MIT
mod_authors=Des Herriott
mod_description=Modular Routers is a highly flexible mod for moving items/fluids/energy around the world in various ways.
modrinth_project_id=EuTS81Z3
curse_project_id=250294

# Minecraft/Forge
minecraft_version=26.2
minecraft_version_range=[26.2,)
neo_version=26.2.0.6-beta
neo_version_range=[26.2.0.1-beta,)
loader_version_range=[4,)
pack_format_number=94.1
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20

# Dependencies
top_version=1.21_neo-12.0.3-5
jade_curse_id=8265965
jei_version=29.5.0.26
patchouli_version=1.21-87-NEOFORGE
ffs_version=26.1.2.1-SNAPSHOT

# Prevent NG attempting to make the test sourceset a junit one
neogradle.subsystems.conventions.sourcesets.automatic-inclusion=false
